FROM ubuntu

MAINTAINER wesley10 (ngouloubiw@gmail.com)

RUN apt-get update
RUN apt-get install -y nginx
EXPOSE 80
#ADD projet-docker /var/www/html/
RUN rm -rf /var/www/html/*
RUN git clone https://github.com/wesleyngouloubi/projet-docker.git  
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]

